---@diagnostic disable: undefined-global
local addonName, ham = ...

function ham.getDrinkForMists()
  return {
    -- Conjured water first: free and doesn't consume bag space or gold
    ham.conjuredManaBuns,
    ham.conjuredManaPudding,
    -- Dual restore (health AND mana, no stats) - shared with Core/Food/Mists.lua's list
    ham.lemonFlowerPudding,
    ham.madBrewersBreakfast,
    ham.freezeDriedHyenaJerky,
    ham.ginsengTea,
    ham.kRE,
    ham.megaFood4000,
    ham.perfectlyCookedInstantNoodles,
    ham.perpetualLeftovers,
    ham.scorpionCrunchies,
    -- Plain water (no stats), highest tier first
    ham.coboCola,
    ham.jadeWitchBrew,
    ham.funkyMonkeyBrew,
    ham.goldenCarpConsomme,
    ham.lotusWater,
    ham.timelessTea,
    ham.cupOfKafa,
    ham.carbonatedWater,
    ham.viseclawSoup,
    ham.blackTea,
    ham.jasmineTea,
    -- Cata, Wrath, TBC, and Classic Era items, as a fallback for lower-level characters
    -- Cata: conjured water
    ham.conjuredManaCake,
    ham.conjuredManaLollipop,
    ham.conjuredManaCupcake,
    ham.conjuredManaBrownie,
    ham.conjuredManaCookie,
    -- Cata: dual restore (health AND mana, no stats)
    ham.scaldingMurglesnout,
    -- Cata: plain water (no stats), highest tier first
    ham.highlandSpringWater,
    ham.invigoratingPineapplePunch,
    ham.meisMasterfulBrew,
    ham.sasparillaSinker,
    ham.southIslandIcedTea,
    ham.starfireEspresso,
    ham.fungusSqueezings,
    ham.greasyWhaleMilk,
    ham.sparklingOasisWater,
    ham.freshWater,
    ham.murkyWater,
    ham.sweetTea,
    ham.garrsLimeade,
    ham.briarootBrew,
    ham.earlBlackTea,
    ham.filteredBilgeWater,
    ham.gilneasSpringWater,
    ham.refreshingPineapplePunch,
    ham.volcanicSpringWater,
    ham.tarpCollectedDew,
    ham.stormwindSurprise,
    ham.wellWater,
    -- Wrath: conjured water
    ham.conjuredManaStrudel,
    ham.conjuredManaPie,
    -- Wrath: dual restore (health AND mana, no stats)
    ham.blackJelly,
    ham.giganticFeast,
    ham.grilledBonescale,
    ham.sauteedGoby,
    ham.smallFeast,
    ham.smokedRockfin,
    -- Wrath: plain water (no stats), highest tier first
    ham.crusadersWaterskin,
    ham.honeymintTea,
    ham.kungaloosh,
    ham.starsSorrow,
    ham.yetiMilk,
    ham.bitterPlasma,
    ham.freshAppleJuice,
    ham.freshSqueezedLimeade,
    ham.pungentSealWhey,
    ham.frostberryJuice,
    ham.grizzleberryJuice,
    ham.mountainWater,
    ham.sweetenedGoatsMilk,
    -- TBC: conjured water
    ham.conjuredGlacierWater,
    ham.conjuredMountainSpringWater,
    -- TBC: dual restore (health AND mana, no stats)
    ham.conjuredMannaBiscuit,
    ham.hotButteredTrout,
    ham.naaruRation,
    ham.enrichedTeroconeJuice,
    ham.undersporePod,
    -- TBC: plain water (no stats), highest tier first
    ham.blackCoffee,
    ham.blackrockFortifiedWater,
    ham.dosOgris,
    ham.ethermead,
    ham.gilneasSparklingWater,
    ham.purifiedDraenicWater,
    ham.sparklingSouthshoreCider,
    ham.starsTears,
    ham.blackrockMineralWater,
    ham.filteredDraenicWater,
    ham.silverwine,
    ham.starsLament,
    ham.blackrockSpringWater,
    -- Classic Era: conjured water
    ham.conjuredCrystalWater,
    ham.conjuredSparklingWater,
    ham.conjuredMineralWater,
    ham.conjuredSpringWater,
    ham.conjuredPurifiedWater,
    ham.conjuredFreshWater,
    ham.conjuredWater,
    -- Classic Era: dual restore (health AND mana, no stats)
    ham.essenceMango,
    ham.enrichedMannaBiscuit,
    ham.alteracMannaBiscuit,
    ham.graccusMinceMeatFruitcake,
    ham.bobbingApple,
    ham.refreshingRedApple,
    ham.cookedCrabClaw,
    ham.sengginRoot,
    ham.greenTeaLeaf,
    -- Classic Era: plain water (no stats), highest tier first
    ham.hyjalNectar,
    ham.morningGloryDew,
    ham.moonberryJuice,
    ham.bottledWinterspringWater,
    ham.sweetNectar,
    ham.enchantedWater,
    ham.goldthornTea,
    ham.melonJuice,
    ham.bubblingWater,
    ham.fizzyFaireDrink,
    ham.iceColdMilk,
    ham.blendedBeanBrew,
    ham.refreshingSpringWater,
}
end
